config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'books#index'
  resources :books do
   resources :comments, only: :create
   collection do
    get 'search'
   end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :category_id,     presence: true
  validates :title,           presence: true
  validates :author,          presence: true
  validates :description,     presence: true
  validates :image,           presence: true
  
  has_one_attached :image
  belongs_to       :user
  has_many         :comments,  dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  validates :category_id,           numericality:{ other_than: 1 ,}

 def self.search(search)
  if search != ""
    Book.where('title LIKE(?)', "%#{search}%")
  else
    Book.all
  end
 end
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'マンガ・コミック' },
    { id: 3, name: '小説' },
    { id: 4, name: '趣味・生活関連の実用書' },
    { id: 5, name: '雑誌(マンガ以外)' },
    { id: 6, name: 'ビジネス書' },
    { id: 7, name: 'マンガ雑誌' },
    { id: 8, name: 'ノンフィクション' },
    { id: 9, name: 'エッセイ' },
    { id: 10, name: 'ライトノベル' },
    { id: 11, name: '語学・資格関連' },
    { id: 12, name: '写真集' },
    { id: 13, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :books
  end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content,      presence: true
  validates :book,         presence: true
  validates :user,         presence: true

  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name,                 presence: true

         has_many :books, dependent: :destroy
         has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth
  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
  def configure_permitted_parameters    
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])  
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :move_to_index,      only:   [:edit, :update, :destroy]
  
  

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to action: 'index'
    else
      @book = Book.new(book_params)
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
    @comment = Comment.new
    @comments = @book.comments
  end

  def edit
    @book = Book.find(params[:id])   
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to action: 'show'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to action: 'index'
  end

  def search
    @books = Book.search(params[:keyword])
  end

  private
  def book_params
    params.require(:book).permit(:image, :category_id, :title, :author, :description).merge(user_id: current_user.id)
  end

  def move_to_index
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to action: :index
    end    
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      redirect_to book_path(@comment.book)
    else
      @book = @comment.book
      @comments = @book.comments
      render "books/show" 
    end      
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, book_id: params[:book_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/books/_book.html.erb
<div class="card">
  <%= link_to image_tag(book.image, class: :card__img ), book_path(book.id) %>
  <div class="card__body">
    <%= link_to book.title, book_path(book.id), class: :card__title%>
    <p class="card__summary">
      <%= book.author %>
    </p>
    <%= link_to "by" + book.user.name, root_path, class: :card__user %>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with model: @book, local: true do |f|%>
  <div class="field">
    <%= f.label :image, "本の画像" %><br />
    <%= f.file_field :image, id:"book_image" %>
  </div>
  <div class="field">
    <%= f.label :category_id, "カテゴリー" %><br />
    <%= f.collection_select(:category_id,  Category.all, :id, :name, {}, {class:"field", id:"book-category"}) %>
  </div>

  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, class: :form__text, id:"book_title" %>
  </div>

  <div class="field">
    <%= f.label :author, "著者" %><br />
    <%= f.text_field :author, class: :form__text, id:"book_author" %>
  </div>

  <div class="field">
    <%= f.label :description, "内容" %><br />
    <%= f.text_area :description, class: :form__text, id:"book_description" %>
  </div>

  

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ブックレコードの編集</h2>      
      <%= render partial: "form" %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
       <div class="greeting" >
        <%= "ようこそ！" %>
         <%= link_to current_user.name, root_path, class: :greeting__link%>
        <%= "さん" %>
       </div> 
   <% end %>
    <div class="card__wrapper">
      <%= render partial: "book", collection: @books %>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">読み終えた本の投稿</h2>
        <%= render partial: "form" %>
    </div>
  </div>
</div>

app/views/books/search.html.erb
  
    <div class="card__wrapper">
      <%= render partial: "book", collection: @books %>
    </div>
  </div>

app/views/books/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @book.title %>
      </p>
      <%= link_to "by" + @book.user.name, root_path, class: :prototype__user %>
      <% if user_signed_in? && current_user.id == @book.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_book_path(@book), class: :prototype__btn %>
          <%= link_to "削除する", book_path(@book), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <div class="prototype__image">
        <%= image_tag @book.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">著者</p>
          <p class="detail__message">
            <%= @book.author %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">カテゴリー</p>
          <p class="detail__message">
            <%= @book.category.name %>
          </p>
        </div>        
        <div class="prototype__detail">
          <p class="detail__title">内容</p>
          <p class="detail__message">
            <%= @book.description %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
         <% if user_signed_in? %>
           <%= form_with model: [@book,@comment],local: true do |f|%>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
               <%= f.submit "送信する", class: :form__btn  %>
            </div>
           <% end %>
         <% end %>      
        <ul class="comments_lists">
          <% @comments.each do |comment| %> 
          <li class="comments_list">                   
           <%= comment.content %>
           <%= link_to comment.user.name, root_path, class: :comment_user %>          
          </li>
          <% end %>
        </ul> 
     </div>              
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookRecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
      <div class="inner">
        <div class="nav">        
          <div class="nav__left">
            <%= link_to image_tag("logo1.png", class: :logo), root_path %>            
          </div>
          <%= form_with(url: search_books_path, local: true, method: :get, class: "search-form") do |form| %>
            <%= form.text_field :keyword, placeholder: "投稿した本を検索する", class: "search-input" %>
            <%= form.submit "検索", class: "search-btn" %>
          <% end %>             
             <% if user_signed_in? %>                           
             <div class="nav__right"> 
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
               <%= link_to "Book Record", new_book_path,  class: :nav__btn %>                             
             </div>
              <% else %>                                                  
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
             <% end %>          
        </div>
      </div>
    </header>      
    <%= yield %>
    <footer class="footer">
      <p class="copyright"> © BOOK RECORD All rights reserved.</p>
    </footer>
  </body>
</html>